version: '2'
services:
  monit:
    image: popov1024/monit-alpine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./monit.d/:/etc/monit.d/
      - ./monitrc:/etc/monitrc:ro
    ports:
      - 2812:2812